// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQoPOBbiGqn7XmdQSIw2j-nJOUdCYedU',
    appId: '1:1056355062042:web:c7bc80932367aef9ae1ca3',
    messagingSenderId: '1056355062042',
    projectId: 'feedback-app-a488f',
    authDomain: 'feedback-app-a488f.firebaseapp.com',
    storageBucket: 'feedback-app-a488f.appspot.com',
    measurementId: 'G-GYKJP03751',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWe_o3BJMTemYMdn93pDTAmvXSWXMgI84',
    appId: '1:1056355062042:android:39c2c051007ce1a1ae1ca3',
    messagingSenderId: '1056355062042',
    projectId: 'feedback-app-a488f',
    storageBucket: 'feedback-app-a488f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbDRFxmMPXM07XS4n-KeNddqGMD7LmyY',
    appId: '1:1056355062042:ios:034ede3cf797e436ae1ca3',
    messagingSenderId: '1056355062042',
    projectId: 'feedback-app-a488f',
    storageBucket: 'feedback-app-a488f.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbDRFxmMPXM07XS4n-KeNddqGMD7LmyY',
    appId: '1:1056355062042:ios:45bc9cf9a8a9897aae1ca3',
    messagingSenderId: '1056355062042',
    projectId: 'feedback-app-a488f',
    storageBucket: 'feedback-app-a488f.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
